# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\ttransport\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"8\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"\xa3\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12$\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x13.transport.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"K\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x03\x32\xa8\x01\n\x04Raft\x12L\n\x0bRequestVote\x12\x1d.transport.RequestVoteRequest\x1a\x1e.transport.RequestVoteResponse\x12R\n\rAppendEntries\x12\x1f.transport.AppendEntriesRequest\x1a .transport.AppendEntriesResponseB\x1cZ\x1akvstore/internal/transportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032kvstore/internal/transport'
  _globals['_REQUESTVOTEREQUEST']._serialized_start=25
  _globals['_REQUESTVOTEREQUEST']._serialized_end=128
  _globals['_REQUESTVOTERESPONSE']._serialized_start=130
  _globals['_REQUESTVOTERESPONSE']._serialized_end=187
  _globals['_LOGENTRY']._serialized_start=189
  _globals['_LOGENTRY']._serialized_end=245
  _globals['_APPENDENTRIESREQUEST']._serialized_start=248
  _globals['_APPENDENTRIESREQUEST']._serialized_end=411
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=413
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=488
  _globals['_RAFT']._serialized_start=491
  _globals['_RAFT']._serialized_end=659
# @@protoc_insertion_point(module_scope)
